# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.IntegerField()),
                ('colorid', models.IntegerField()),
                ('sizeid', models.IntegerField()),
                ('count', models.PositiveIntegerField()),
                ('isdelete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set([('goodsid', 'colorid', 'sizeid')]),
        ),
    ]
