# Generated by Django 2.0.4 on 2018-05-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name_plural': '帖子'},
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
