# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.ImageField(upload_to='media/color/')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u989c\u8272',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('desc', models.CharField(max_length=100, verbose_name='\u5546\u54c1\u63cf\u8ff0')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u73b0\u4ef7')),
                ('oldprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u539f\u4ef7')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='GoodsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='GoodsDetailsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.ImageField(upload_to='media/', verbose_name='\u56fe\u7247')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
                ('goodsdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsDetails', verbose_name='\u8be6\u60c5')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u8be6\u7ec6\u6761\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Color')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u5e93\u5b58',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u5c3a\u5bf8',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Size'),
        ),
    ]
