# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbBookcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('column_3', models.CharField(blank=True, db_column='Column_3', max_length=10, null=True)),
            ],
            options={
                'db_table': 'tb_bookcase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbBookinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=30, null=True)),
                ('bookname', models.CharField(blank=True, max_length=70, null=True)),
                ('typeid', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=30, null=True)),
                ('translator', models.CharField(blank=True, max_length=30, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('bookcase', models.IntegerField(blank=True, null=True)),
                ('intime', models.DateField(blank=True, db_column='inTime', null=True)),
                ('operator', models.CharField(blank=True, max_length=30, null=True)),
                ('del_field', models.IntegerField(blank=True, db_column='del', null=True)),
            ],
            options={
                'db_table': 'tb_bookinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbBooktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(blank=True, max_length=30, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_booktype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readerid', models.IntegerField(blank=True, null=True)),
                ('bookid', models.IntegerField(blank=True, null=True)),
                ('borrowtime', models.DateField(blank=True, db_column='borrowTime', null=True)),
                ('backtime', models.DateField(blank=True, db_column='backTime', null=True)),
                ('operator', models.CharField(blank=True, max_length=30, null=True)),
                ('ifback', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_borrow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbGiveback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readerid', models.IntegerField(blank=True, null=True)),
                ('bookid', models.IntegerField(blank=True, null=True)),
                ('backtime', models.DateField(blank=True, db_column='backTime', null=True)),
                ('operator', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tb_giveback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libraryname', models.CharField(blank=True, max_length=50, null=True)),
                ('curator', models.CharField(blank=True, max_length=10, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('createdate', models.DateField(blank=True, db_column='createDate', null=True)),
                ('introduce', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_library',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('pwd', models.CharField(blank=True, db_column='PWD', max_length=30, null=True)),
            ],
            options={
                'db_table': 'tb_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('validity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbPublishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=20, null=True)),
                ('pubname', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tb_publishing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbPurview',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sysset', models.IntegerField(blank=True, null=True)),
                ('readerset', models.IntegerField(blank=True, null=True)),
                ('bookset', models.IntegerField(blank=True, null=True)),
                ('borrowback', models.IntegerField(blank=True, null=True)),
                ('sysquery', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_purview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=4, null=True)),
                ('barcode', models.CharField(blank=True, max_length=30, null=True)),
                ('vocation', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('papertype', models.CharField(blank=True, db_column='paperType', max_length=10, null=True)),
                ('paperno', models.CharField(blank=True, db_column='paperNO', max_length=20, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('createdate', models.DateField(blank=True, db_column='createDate', null=True)),
                ('operator', models.CharField(blank=True, max_length=30, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('typeid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_reader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbReadertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_readertype',
                'managed': False,
            },
        ),
    ]
